def seeding_charachers
  User.create!(name: "Aegon", family_name: "Targaryen", email: "aegon@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Visenya", family_name: "Targaryen", email: "visenya@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Aenys", family_name: "Targaryen", email: "aenys@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Jaehaerys", family_name: "Targaryen", email: "jaehaerys@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Alysanne", family_name: "Targaryen", email: "alysanne@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Rhaenys", family_name: "Targaryen", email: "rhaenys_qwnw@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Leanor", family_name: "Velarion", email: "leanor@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Rhaenyra", family_name: "Targaryen", email: "rhaenyra@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Aegon II", family_name: "Targaryen", email: "aegonII@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Daemon", family_name: "Targaryen", email: "daemon@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Jacaerys", family_name: "Velaryon", email: "jace@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Lucerys", family_name: "Targaryen", email: "luke@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Baela", family_name: "Targaryen", email: "baela@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Haelena", family_name: "Targaryen", email: "haelena@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Joffrey", family_name: "Targaryen", email: "joffrey@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Laena", family_name: "Velaryon", email: "laena@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Aemond", family_name: "Targaryen", email: "aemond@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Viserys II", family_name: "Targaryen", email: "viserys@dr.com", password: "dracarys", password_confirmation: "dracarys")
  User.create!(name: "Danaerys", family_name: "Targaryen", email: "dany@dr.com", password: "dracarys", password_confirmation: "dracarys")
end
